name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools
        uses: ./.github/actions/asdf-install

      - name: Run lint
        run: uv run ruff check

      - name: Run format
        run: uv run ruff format --check

      - name: Run tests
        run: uv run pytest --tb=short -p no:warnings -p no:cacheprovider
