name: CI

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools
        uses: ./.github/actions/asdf-install

      - name: Run lint
        run: uv run ruff check

      - name: Run format
        run: uv run ruff format --check

      - name: Run tests
        run: uv run pytest --tb=short -p no:warnings -p no:cacheprovider

  if_merged:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install tools
        uses: ./.github/actions/asdf-install
      - name: Create bump and changelog
        id: cz
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md
          push: false
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: release-${{ steps.cz.outputs.version }}
